### ISSUE TITLE
Getting token error and no data

### ISSUE THREAD

**Issue by kailledargun** [tlkamp/litter-api#9]
Quite recently the litter exporter has stopped reporting data. Docker log reports below. Any idea what may be wrong? I have tried using env variables or flags on cmd but no combo seems to work. Appreciate any advice!

time="2023-08-30T01:16:29Z" level=fatal msg="token contains an invalid number of segments"
time="2023-08-30T01:16:32Z" level=error msg="failed to parse token claims" error="token contains an invalid number of segments"

**Comment by tlkamp** [comment]
Thanks for the report. This looks like the JWT response from the auth endpoint is invalid. I'll investigate further but in the mean time I recommend making sure your username and password are correct and you haven't been locked out of the app/website.

**Comment by tlkamp** [comment]
Looks like I'm also receiving the error - https://github.com/tlkamp/litter-api/actions/runs/6019442097/job/16329275967 

I'll investigate further as I have time.

**Comment by kailledargun** [comment]
Thanks. I really appreciate it. I love having that data available. It makes life easier to see on our home calendars.

**Comment by tlkamp** [comment]
@kailledargun I've discovered the issue, it appears the authentication mechanism has changed quite a bit. I'm working on fixing it, but it's probably going to take a little while. I'll let you know when it's ready. Thanks for your patience!

**Comment by kailledargun** [comment]
Thanks so much for your effort. I will be more than happy to wait. I really appreciate this project!

**Comment by tlkamp** [comment]
Hi @kailledargun! Please update to the latest release of litter-exporter `v3.0.0` and confirm it's working :)

**Comment by kailledargun** [comment]
Works perfect! Thanks!!!
